<?php

define('URBIT_PRODUCT_FEED_PLUGIN_DIR', dirname(__FILE__));
define('URBIT_PRODUCT_FEED_CLASS_DIR', URBIT_PRODUCT_FEED_PLUGIN_DIR . '/classes');
define('URBIT_PRODUCT_FEED_INCLUDES_DIR', URBIT_PRODUCT_FEED_PLUGIN_DIR . '/includes');

//admin
define('URBIT_PRODUCT_FEED_ADMIN_CLASS_DIR', URBIT_PRODUCT_FEED_CLASS_DIR . '/admin');